name: Linting

on:
  push:
    branches:
      - mainline
      - future
  pull_request:
    branches:
      - mainline

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Discord Stubs
      uses: actions/checkout@v2
      with:
        repository: "bryanforbes/discord.py"
        ref:  "typings"
        path: "discord.stub"

    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run:  pip install -r requirements.txt

    - name: Install Linters
      run:  pip install flake8 mypy black

    - name: Run Linters
      uses: samuelmeuli/lint-action@v1
      env:
        MYPYPATH: "$GITHUB_WORKSPACE/discord.stub"
      with:
        github_token: ${{ secrets.github_token }}

        black:  true
        flake8: true
        mypy:   true
        mypy_flags: --strict
